x-airflow-common: &airflow-common
  build: . # build from your Dockerfile
  image: airflow-with-dbt:latest

  environment: &airflow-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__WEBSERVER__DEFAULT_UI_THEME: dark
    DB_USER: ${POSTGRES_USER}
    DB_PASSWORD: ${POSTGRES_PASSWORD}
    DB_HOST: postgres
    DB_PORT: 5432
    DB_NAME: ${POSTGRES_DB}


  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./dbt_project:/home/airflow/dbt_projects
    - ./scripts:/home/airflow/scripts
    - ./data:/opt/airflow/data
    - /home/abuammar/.dbt:/home/airflow/.dbt

  user: "${AIRFLOW_UID:-1000}:0"
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5431:5432"

  adminer:
    image: adminer
    container_name: adminer_ui
    ports:
      - "8083:8080"
    depends_on:
      - postgres

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  airflow-init:
    <<: *airflow-common
    command: >
            bash -c "airflow db upgrade && airflow users create --username ${AIRFLOW_ADMIN_USER} --password ${AIRFLOW_ADMIN_PASSWORD} --firstname Airflow --lastname Admin --role Admin --email ${AIRFLOW_ADMIN_EMAIL}"
            
volumes:
  postgres-db-volume:

# HOW TO RUN LOCALLY
# mkdir -p dags logs plugins dbt_project
# export AIRFLOW_UID=$(id -u)
# sudo chown -R $AIRFLOW_UID:0 dags logs plugins dbt_project
# docker compose down -v
# docker compose up airflow-init   # initialize db
# docker compose up -d             # start everything
